apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
        - image: asia.gcr.io/$PROJECT_ID/wdpress/hello-world
          imagePullPolicy: Always
          name: hello-world
